<div>
    <label>
        Имя
        <input type="text" name="user[name]" value="<?= htmlspecialchars($userData['name'] ?? '') ?>">
    </label>
    <?php if (isset($errors['name'])): ?>
        <div><?= $errors['name'] ?></div>
    <?php endif ?>
</div>
<div>
    <label>
        email
    </label>
       <input type="text" name="user[email]" value="<?= htmlspecialchars($userData['email'] ?? '') ?>">  
    <?php if (isset($errors['mail'])): ?>
        <div><?= $errors['mail'] ?></div>
    <?php endif ?>
</div>
