<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
<input type="hidden" name="_METHOD" value="PATCH">

    <div>
      <label>
          name
          <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['name'])): ?>
          <div><?= $errors['name'] ?></div>
      <?php endif ?>
      <label>
          mail
          <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['mail'])): ?>
          <div><?= $errors['mail'] ?></div>
      <?php endif ?>
          id
          <input type="text" name="user[id]" value="<?= htmlspecialchars($user['id'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['id'])): ?>
          <div><?= $errors['id'] ?></div>
      <?php endif ?>

    </div>
    <input type="submit" value="Update">
</form>