<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>

<a href="/users/new">Новый пользователь</a>

<?php foreach ($users as $user) : ?>
  <div>
      <a href="/users/<?= $user['id'] ?>/edit"><?= htmlspecialchars($user['name']) ?></a>
      <form action="/users/<?= $user['id'] ?>" method="post">
      <input type="hidden" name="_METHOD" value="DELETE">
      <input type="submit" value="Delete">
    </form>
  </div>
<?php endforeach ?>

